sudo: required
services:
  - docker

before_install:
  - docker build -t malexandroff1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true malexandroff1/react-test npm test -- --coverage

after_success:
  - docker build -t malexandroff1/multi-client ./client
  - docker build -t malexandroff1/multi-nginx ./nginx
  - docker build -t malexandroff1/multi-server ./server
  - docker build -t malexandroff1/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push malexandroff1/multi-client
  - docker push malexandroff1/multi-nginx
  - docker push malexandroff1/multi-server
  - docker push malexandroff1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-099648140551
  bucket_path: docker-react-demo
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"